project:
  type: book
  output-dir: _book

book:
  title: "Contributing to Stan"
  subtitle: "A Developer’s Guide to the Core, Interfaces, and First Contributions"
  author: "Florence Bockting"
  date: today
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-what-is-stan.qmd
    - 02-stan-ecosystem.qmd
    - 03-how-to-contribute.qmd
    - 04-find-information.qmd
    - 05-checklist.qmd

format:
  html:
    toc: true
    number-sections: true
    embed-resources: true
    code-fold: false
    css: book.css
  pdf:
    documentclass: scrreprt
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    keep-tex: false

execute:
  echo: true
  eval: true
  freeze: auto
